# Copyright 2026 Jeff Koftinoff <jeff.koftinoff@statusbar.com>
# SPDX-License-Identifier: MIT
"""IEEE 1722-2025 clause 9.4 ACF message layouts (Table 23 types 9.4.2 to 9.4.19).

One entry per message type: the fixed part after the two-octet common header
(offsets are from the start of the message, including that header), the
payload rule and the clause's bounds. This is the same table the C++
``avtp_acf_<name>.hpp`` headers were generated from; ``test_value`` is the value
each field takes in the golden capture. ``kind``: ``bool`` (one flag bit),
``uint`` (a masked field), ``whole`` (an entire integer or EUI-48 member).
``pad_mode``: ``field`` (a pad field counts trailing zero octets), ``custom``
(padding follows from the fields: PARALLEL bit_width, SENSOR num_sensors x sz),
``none`` (no pad field; the payload is taken as carried).
"""

from __future__ import annotations

ACF_TYPES: list[dict] = [
    {
        "name": "flexray",
        "Name": "Flexray",
        "clause": "9.4.2",
        "figure": "Figure 64",
        "title": "FlexRay message",
        "msg_type": 0,
        "length": 0x10,
        "min_q": 0,
        "max_q": 0x40,
        "brief": False,
        "pad_mode": "field",
        "fixed_only": False,
        "fields": [
            {
                "name": "pad",
                "offset": 2,
                "length": 1,
                "kind": "uint",
                "mask": 0xC0,
                "shift": 6,
                "ctype": "u8",
                "hex": False,
                "test_value": 2,
                "doc": "padding octets at the end of the payload (0 to 3)",
            },
            {
                "name": "mtv",
                "offset": 2,
                "length": 1,
                "kind": "bool",
                "mask": 0x20,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "message_timestamp valid",
            },
            {
                "name": "fr_bus_id",
                "offset": 2,
                "length": 1,
                "kind": "uint",
                "mask": 0x1F,
                "shift": 0,
                "ctype": "u8",
                "hex": False,
                "test_value": 0x15,
                "doc": "FlexRay bus identifier (application specific, Annex L)",
            },
            {
                "name": "chan",
                "offset": 3,
                "length": 1,
                "kind": "uint",
                "mask": 0x30,
                "shift": 4,
                "ctype": "u8",
                "hex": False,
                "test_value": 2,
                "doc": "source channel (Table 25: 0 unknown, 1 A, 2 B, 3 both)",
            },
            {
                "name": "str",
                "offset": 3,
                "length": 1,
                "kind": "bool",
                "mask": 8,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "startup frame indicator",
            },
            {
                "name": "syn",
                "offset": 3,
                "length": 1,
                "kind": "bool",
                "mask": 4,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "sync frame indicator",
            },
            {
                "name": "pre",
                "offset": 3,
                "length": 1,
                "kind": "bool",
                "mask": 2,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "payload preamble indicator",
            },
            {
                "name": "nfi",
                "offset": 3,
                "length": 1,
                "kind": "bool",
                "mask": 1,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "null frame indicator",
            },
            {
                "name": "message_timestamp",
                "offset": 4,
                "length": 8,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u64",
                "hex": False,
                "test_value": 0x102030405060708,
                "doc": "acquisition time in ns (9.4.1.5)",
            },
            {
                "name": "fr_frame_id",
                "offset": 12,
                "length": 4,
                "kind": "uint",
                "mask": 0xFFE00000,
                "shift": 0x15,
                "ctype": "u16",
                "hex": True,
                "test_value": 0x5A5,
                "doc": "FlexRay frame identifier (1 to 2047, 0 when not from FlexRay)",
            },
            {
                "name": "cycle",
                "offset": 12,
                "length": 4,
                "kind": "uint",
                "mask": 0x3F,
                "shift": 0,
                "ctype": "u8",
                "hex": False,
                "test_value": 0x2A,
                "doc": "FlexRay cycle count",
            },
        ],
    },
    {
        "name": "can",
        "Name": "Can",
        "clause": "9.4.3",
        "figure": "Figure 65",
        "title": "CAN/CAN FD message",
        "msg_type": 1,
        "length": 0x10,
        "min_q": 0,
        "max_q": 0x10,
        "brief": False,
        "pad_mode": "field",
        "fixed_only": False,
        "fields": [
            {
                "name": "pad",
                "offset": 2,
                "length": 1,
                "kind": "uint",
                "mask": 0xC0,
                "shift": 6,
                "ctype": "u8",
                "hex": False,
                "test_value": 1,
                "doc": "padding octets at the end of the payload (0 to 3)",
            },
            {
                "name": "mtv",
                "offset": 2,
                "length": 1,
                "kind": "bool",
                "mask": 0x20,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "message_timestamp valid",
            },
            {
                "name": "rtr",
                "offset": 2,
                "length": 1,
                "kind": "bool",
                "mask": 0x10,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "remote transmission request (CAN CC only)",
            },
            {
                "name": "eff",
                "offset": 2,
                "length": 1,
                "kind": "bool",
                "mask": 8,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "extended frame format: 29-bit identifier when set, 11-bit when clear",
            },
            {
                "name": "brs",
                "offset": 2,
                "length": 1,
                "kind": "bool",
                "mask": 4,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "bit rate switch (CAN FD only)",
            },
            {
                "name": "fdf",
                "offset": 2,
                "length": 1,
                "kind": "bool",
                "mask": 2,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "CAN FD format: payload may be 0-8, 12, 16, 20, 24, 32, 48 or 64 octets",
            },
            {
                "name": "esi",
                "offset": 2,
                "length": 1,
                "kind": "bool",
                "mask": 1,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "error state indicator (CAN FD only)",
            },
            {
                "name": "can_bus_id",
                "offset": 3,
                "length": 1,
                "kind": "uint",
                "mask": 0x1F,
                "shift": 0,
                "ctype": "u8",
                "hex": False,
                "test_value": 0x13,
                "doc": "CAN bus identifier, 5 bits (application specific, Annex L)",
            },
            {
                "name": "message_timestamp",
                "offset": 4,
                "length": 8,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u64",
                "hex": False,
                "test_value": 0x102030405060708,
                "doc": "acquisition time in ns (9.4.1.5)",
            },
            {
                "name": "can_identifier",
                "offset": 12,
                "length": 4,
                "kind": "uint",
                "mask": 0x1FFFFFFF,
                "shift": 0,
                "ctype": "u32",
                "hex": True,
                "test_value": 0x1ABCDEF,
                "doc": "CAN identifier, 11 or 29 bits per eff, right-aligned",
            },
        ],
    },
    {
        "name": "can_v2",
        "Name": "CanV2",
        "clause": "9.4.3",
        "figure": "Figure 66",
        "title": "CAN/CAN FD message version 2",
        "msg_type": 0x21,
        "length": 0x10,
        "min_q": 0,
        "max_q": 0x10,
        "brief": False,
        "pad_mode": "field",
        "fixed_only": False,
        "fields": [
            {
                "name": "pad",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0xC000,
                "shift": 0xE,
                "ctype": "u8",
                "hex": False,
                "test_value": 1,
                "doc": "padding octets at the end of the payload (0 to 3)",
            },
            {
                "name": "mtv",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 0x2000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "message_timestamp valid",
            },
            {
                "name": "rtr",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 0x1000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "remote transmission request (CAN CC only)",
            },
            {
                "name": "eff",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 0x800,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "extended frame format: 29-bit identifier when set, 11-bit when clear",
            },
            {
                "name": "can_bus_id",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0x7FF,
                "shift": 0,
                "ctype": "u16",
                "hex": False,
                "test_value": 0x5AB,
                "doc": "CAN bus identifier, 11 bits (application specific, Annex L)",
            },
            {
                "name": "message_timestamp",
                "offset": 4,
                "length": 8,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u64",
                "hex": False,
                "test_value": 0x102030405060708,
                "doc": "acquisition time in ns (9.4.1.5)",
            },
            {
                "name": "brs",
                "offset": 12,
                "length": 4,
                "kind": "bool",
                "mask": 0x80000000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "bit rate switch (CAN FD only)",
            },
            {
                "name": "fdf",
                "offset": 12,
                "length": 4,
                "kind": "bool",
                "mask": 0x40000000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "CAN FD format: payload may be 0-8, 12, 16, 20, 24, 32, 48 or 64 octets",
            },
            {
                "name": "esi",
                "offset": 12,
                "length": 4,
                "kind": "bool",
                "mask": 0x20000000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "error state indicator (CAN FD only)",
            },
            {
                "name": "can_identifier",
                "offset": 12,
                "length": 4,
                "kind": "uint",
                "mask": 0x1FFFFFFF,
                "shift": 0,
                "ctype": "u32",
                "hex": True,
                "test_value": 0x1ABCDEF,
                "doc": "CAN identifier, 11 or 29 bits per eff, right-aligned",
            },
        ],
    },
    {
        "name": "can_brief",
        "Name": "CanBrief",
        "clause": "9.4.4",
        "figure": "Figure 68",
        "title": "Abbreviated CAN/CAN FD message",
        "msg_type": 2,
        "length": 8,
        "min_q": 0,
        "max_q": 0x10,
        "brief": True,
        "pad_mode": "field",
        "fixed_only": False,
        "fields": [
            {
                "name": "pad",
                "offset": 2,
                "length": 1,
                "kind": "uint",
                "mask": 0xC0,
                "shift": 6,
                "ctype": "u8",
                "hex": False,
                "test_value": 1,
                "doc": "padding octets at the end of the payload (0 to 3)",
            },
            {
                "name": "mtv",
                "offset": 2,
                "length": 1,
                "kind": "bool",
                "mask": 0x20,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "message_timestamp valid - always zero on a brief message (9.4.4.1)",
            },
            {
                "name": "rtr",
                "offset": 2,
                "length": 1,
                "kind": "bool",
                "mask": 0x10,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "remote transmission request (CAN CC only)",
            },
            {
                "name": "eff",
                "offset": 2,
                "length": 1,
                "kind": "bool",
                "mask": 8,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "extended frame format: 29-bit identifier when set, 11-bit when clear",
            },
            {
                "name": "brs",
                "offset": 2,
                "length": 1,
                "kind": "bool",
                "mask": 4,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "bit rate switch (CAN FD only)",
            },
            {
                "name": "fdf",
                "offset": 2,
                "length": 1,
                "kind": "bool",
                "mask": 2,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "CAN FD format: payload may be 0-8, 12, 16, 20, 24, 32, 48 or 64 octets",
            },
            {
                "name": "esi",
                "offset": 2,
                "length": 1,
                "kind": "bool",
                "mask": 1,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "error state indicator (CAN FD only)",
            },
            {
                "name": "can_bus_id",
                "offset": 3,
                "length": 1,
                "kind": "uint",
                "mask": 0x1F,
                "shift": 0,
                "ctype": "u8",
                "hex": False,
                "test_value": 0x13,
                "doc": "CAN bus identifier, 5 bits (application specific, Annex L)",
            },
            {
                "name": "can_identifier",
                "offset": 4,
                "length": 4,
                "kind": "uint",
                "mask": 0x1FFFFFFF,
                "shift": 0,
                "ctype": "u32",
                "hex": True,
                "test_value": 0x1ABCDEF,
                "doc": "CAN identifier, 11 or 29 bits per eff, right-aligned",
            },
        ],
    },
    {
        "name": "can_brief_v2",
        "Name": "CanBriefV2",
        "clause": "9.4.4",
        "figure": "Figure 69",
        "title": "Abbreviated CAN/CAN FD message version 2",
        "msg_type": 0x22,
        "length": 8,
        "min_q": 0,
        "max_q": 0x10,
        "brief": True,
        "pad_mode": "field",
        "fixed_only": False,
        "fields": [
            {
                "name": "pad",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0xC000,
                "shift": 0xE,
                "ctype": "u8",
                "hex": False,
                "test_value": 1,
                "doc": "padding octets at the end of the payload (0 to 3)",
            },
            {
                "name": "mtv",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 0x2000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "message_timestamp valid - always zero on a brief message (9.4.4.1)",
            },
            {
                "name": "rtr",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 0x1000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "remote transmission request (CAN CC only)",
            },
            {
                "name": "eff",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 0x800,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "extended frame format: 29-bit identifier when set, 11-bit when clear",
            },
            {
                "name": "can_bus_id",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0x7FF,
                "shift": 0,
                "ctype": "u16",
                "hex": False,
                "test_value": 0x5AB,
                "doc": "CAN bus identifier, 11 bits (application specific, Annex L)",
            },
            {
                "name": "brs",
                "offset": 4,
                "length": 4,
                "kind": "bool",
                "mask": 0x80000000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "bit rate switch (CAN FD only)",
            },
            {
                "name": "fdf",
                "offset": 4,
                "length": 4,
                "kind": "bool",
                "mask": 0x40000000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "CAN FD format: payload may be 0-8, 12, 16, 20, 24, 32, 48 or 64 octets",
            },
            {
                "name": "esi",
                "offset": 4,
                "length": 4,
                "kind": "bool",
                "mask": 0x20000000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "error state indicator (CAN FD only)",
            },
            {
                "name": "can_identifier",
                "offset": 4,
                "length": 4,
                "kind": "uint",
                "mask": 0x1FFFFFFF,
                "shift": 0,
                "ctype": "u32",
                "hex": True,
                "test_value": 0x1ABCDEF,
                "doc": "CAN identifier, 11 or 29 bits per eff, right-aligned",
            },
        ],
    },
    {
        "name": "lin",
        "Name": "Lin",
        "clause": "9.4.5",
        "figure": "Figure 70",
        "title": "LIN message",
        "msg_type": 3,
        "length": 0xC,
        "min_q": 0,
        "max_q": 2,
        "brief": False,
        "pad_mode": "field",
        "fixed_only": False,
        "fields": [
            {
                "name": "pad",
                "offset": 2,
                "length": 1,
                "kind": "uint",
                "mask": 0xC0,
                "shift": 6,
                "ctype": "u8",
                "hex": False,
                "test_value": 2,
                "doc": "padding octets at the end of the payload (0 to 3)",
            },
            {
                "name": "mtv",
                "offset": 2,
                "length": 1,
                "kind": "bool",
                "mask": 0x20,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "message_timestamp valid",
            },
            {
                "name": "lin_bus_id",
                "offset": 2,
                "length": 1,
                "kind": "uint",
                "mask": 0x1F,
                "shift": 0,
                "ctype": "u8",
                "hex": False,
                "test_value": 0xB,
                "doc": "LIN bus identifier, 5 bits (application specific, Annex L)",
            },
            {
                "name": "lin_identifier",
                "offset": 3,
                "length": 1,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u8",
                "hex": True,
                "test_value": 0x3C,
                "doc": "LIN message identifier",
            },
            {
                "name": "message_timestamp",
                "offset": 4,
                "length": 8,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u64",
                "hex": False,
                "test_value": 0x102030405060708,
                "doc": "acquisition time in ns (9.4.1.5)",
            },
        ],
    },
    {
        "name": "lin_v2",
        "Name": "LinV2",
        "clause": "9.4.5",
        "figure": "Figure 71",
        "title": "LIN message version 2",
        "msg_type": 0x23,
        "length": 0x10,
        "min_q": 0,
        "max_q": 2,
        "brief": False,
        "pad_mode": "field",
        "fixed_only": False,
        "fields": [
            {
                "name": "pad",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0xC000,
                "shift": 0xE,
                "ctype": "u8",
                "hex": False,
                "test_value": 2,
                "doc": "padding octets at the end of the payload (0 to 3)",
            },
            {
                "name": "mtv",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 0x2000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "message_timestamp valid",
            },
            {
                "name": "lin_bus_id",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0x7FF,
                "shift": 0,
                "ctype": "u16",
                "hex": False,
                "test_value": 0x4CD,
                "doc": "LIN bus identifier, 11 bits (application specific, Annex L)",
            },
            {
                "name": "message_timestamp",
                "offset": 4,
                "length": 8,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u64",
                "hex": False,
                "test_value": 0x102030405060708,
                "doc": "acquisition time in ns (9.4.1.5)",
            },
            {
                "name": "lin_identifier",
                "offset": 12,
                "length": 4,
                "kind": "uint",
                "mask": 0xFF,
                "shift": 0,
                "ctype": "u8",
                "hex": True,
                "test_value": 0x3C,
                "doc": "LIN message identifier",
            },
        ],
    },
    {
        "name": "most",
        "Name": "Most",
        "clause": "9.4.6",
        "figure": "Figure 72",
        "title": "MOST message",
        "msg_type": 4,
        "length": 0x14,
        "min_q": 0,
        "max_q": None,
        "brief": False,
        "pad_mode": "field",
        "fixed_only": False,
        "fields": [
            {
                "name": "pad",
                "offset": 2,
                "length": 1,
                "kind": "uint",
                "mask": 0xC0,
                "shift": 6,
                "ctype": "u8",
                "hex": False,
                "test_value": 1,
                "doc": "padding octets at the end of the payload (0 to 3)",
            },
            {
                "name": "mtv",
                "offset": 2,
                "length": 1,
                "kind": "bool",
                "mask": 0x20,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "message_timestamp valid",
            },
            {
                "name": "most_net_id",
                "offset": 2,
                "length": 1,
                "kind": "uint",
                "mask": 0x1F,
                "shift": 0,
                "ctype": "u8",
                "hex": False,
                "test_value": 7,
                "doc": "MOST network identifier (application specific, Annex L)",
            },
            {
                "name": "message_timestamp",
                "offset": 4,
                "length": 8,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u64",
                "hex": False,
                "test_value": 0x102030405060708,
                "doc": "acquisition time in ns (9.4.1.5)",
            },
            {
                "name": "device_id",
                "offset": 12,
                "length": 2,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u16",
                "hex": True,
                "test_value": 0x123,
                "doc": "node address of the source (or, for an answer, the receiver)",
            },
            {
                "name": "fblock_id",
                "offset": 14,
                "length": 1,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u8",
                "hex": True,
                "test_value": 0x45,
                "doc": "MOST function block identifier",
            },
            {
                "name": "inst_id",
                "offset": 15,
                "length": 1,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u8",
                "hex": True,
                "test_value": 0x67,
                "doc": "function block instance",
            },
            {
                "name": "func_id",
                "offset": 16,
                "length": 2,
                "kind": "uint",
                "mask": 0xFFF0,
                "shift": 4,
                "ctype": "u16",
                "hex": True,
                "test_value": 0x89A,
                "doc": "MOST function (12 bits)",
            },
            {
                "name": "op_type",
                "offset": 16,
                "length": 2,
                "kind": "uint",
                "mask": 0xF,
                "shift": 0,
                "ctype": "u8",
                "hex": True,
                "test_value": 0xB,
                "doc": "MOST operation type (4 bits)",
            },
        ],
    },
    {
        "name": "can_xl",
        "Name": "CanXl",
        "clause": "9.4.18",
        "figure": "Figure 92",
        "title": "CAN XL message",
        "msg_type": 0x11,
        "length": 0x18,
        "min_q": 1,
        "max_q": None,
        "brief": False,
        "pad_mode": "field",
        "fixed_only": False,
        "fields": [
            {
                "name": "pad",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0xC000,
                "shift": 0xE,
                "ctype": "u8",
                "hex": False,
                "test_value": 1,
                "doc": "padding octets at the end of the payload (0 to 3; zero when ms is set)",
            },
            {
                "name": "mtv",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 0x2000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "message_timestamp valid",
            },
            {
                "name": "can_bus_id",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0x7FF,
                "shift": 0,
                "ctype": "u16",
                "hex": False,
                "test_value": 0x2AB,
                "doc": "CAN XL bus identifier, 11 bits (application specific, Annex L)",
            },
            {
                "name": "message_timestamp",
                "offset": 4,
                "length": 8,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u64",
                "hex": False,
                "test_value": 0x102030405060708,
                "doc": "acquisition time in ns (9.4.1.5)",
            },
            {
                "name": "vcid",
                "offset": 12,
                "length": 1,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u8",
                "hex": True,
                "test_value": 0x12,
                "doc": "virtual CAN network identifier",
            },
            {
                "name": "sdt",
                "offset": 13,
                "length": 1,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u8",
                "hex": True,
                "test_value": 0x34,
                "doc": "service data unit type",
            },
            {
                "name": "rrs",
                "offset": 14,
                "length": 2,
                "kind": "bool",
                "mask": 0x1000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "remote request substitution",
            },
            {
                "name": "sec",
                "offset": 14,
                "length": 2,
                "kind": "bool",
                "mask": 0x800,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "simple extended content",
            },
            {
                "name": "priority_id",
                "offset": 14,
                "length": 2,
                "kind": "uint",
                "mask": 0x7FF,
                "shift": 0,
                "ctype": "u16",
                "hex": True,
                "test_value": 0x5A5,
                "doc": "priority identifier (11 bits)",
            },
            {
                "name": "acceptance_field",
                "offset": 16,
                "length": 4,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u32",
                "hex": True,
                "test_value": 0xDEADBEEF,
                "doc": "acceptance field",
            },
            {
                "name": "transaction_num",
                "offset": 21,
                "length": 1,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u8",
                "hex": True,
                "test_value": 0x77,
                "doc": "sequence of CAN XL messages; same for every segment of one frame",
            },
            {
                "name": "ms",
                "offset": 22,
                "length": 2,
                "kind": "bool",
                "mask": 0x1000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "more segments follow in later AVTPDUs",
            },
            {
                "name": "segment_num",
                "offset": 22,
                "length": 2,
                "kind": "uint",
                "mask": 0xFFF,
                "shift": 0,
                "ctype": "u16",
                "hex": False,
                "test_value": 0x123,
                "doc": "0 = unsegmented, else the 1-based segment number",
            },
        ],
    },
    {
        "name": "can_xl_brief",
        "Name": "CanXlBrief",
        "clause": "9.4.19",
        "figure": "Figure 93",
        "title": "Abbreviated CAN XL message",
        "msg_type": 0x12,
        "length": 0x10,
        "min_q": 1,
        "max_q": None,
        "brief": True,
        "pad_mode": "field",
        "fixed_only": False,
        "fields": [
            {
                "name": "pad",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0xC000,
                "shift": 0xE,
                "ctype": "u8",
                "hex": False,
                "test_value": 1,
                "doc": "padding octets at the end of the payload (0 to 3; zero when ms is set)",
            },
            {
                "name": "mtv",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 0x2000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "message_timestamp valid - always zero on a brief message (9.4.19.2)",
            },
            {
                "name": "can_bus_id",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0x7FF,
                "shift": 0,
                "ctype": "u16",
                "hex": False,
                "test_value": 0x2AB,
                "doc": "CAN XL bus identifier, 11 bits (application specific, Annex L)",
            },
            {
                "name": "vcid",
                "offset": 4,
                "length": 1,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u8",
                "hex": True,
                "test_value": 0x12,
                "doc": "virtual CAN network identifier",
            },
            {
                "name": "sdt",
                "offset": 5,
                "length": 1,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u8",
                "hex": True,
                "test_value": 0x34,
                "doc": "service data unit type",
            },
            {
                "name": "rrs",
                "offset": 6,
                "length": 2,
                "kind": "bool",
                "mask": 0x1000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "remote request substitution",
            },
            {
                "name": "sec",
                "offset": 6,
                "length": 2,
                "kind": "bool",
                "mask": 0x800,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "simple extended content",
            },
            {
                "name": "priority_id",
                "offset": 6,
                "length": 2,
                "kind": "uint",
                "mask": 0x7FF,
                "shift": 0,
                "ctype": "u16",
                "hex": True,
                "test_value": 0x5A5,
                "doc": "priority identifier (11 bits)",
            },
            {
                "name": "acceptance_field",
                "offset": 8,
                "length": 4,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u32",
                "hex": True,
                "test_value": 0xDEADBEEF,
                "doc": "acceptance field",
            },
            {
                "name": "transaction_num",
                "offset": 13,
                "length": 1,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u8",
                "hex": True,
                "test_value": 0x77,
                "doc": "sequence of CAN XL messages; same for every segment of one frame",
            },
            {
                "name": "ms",
                "offset": 14,
                "length": 2,
                "kind": "bool",
                "mask": 0x1000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "more segments follow in later AVTPDUs",
            },
            {
                "name": "segment_num",
                "offset": 14,
                "length": 2,
                "kind": "uint",
                "mask": 0xFFF,
                "shift": 0,
                "ctype": "u16",
                "hex": False,
                "test_value": 0x123,
                "doc": "0 = unsegmented, else the 1-based segment number",
            },
        ],
    },
    {
        "name": "gpc",
        "Name": "Gpc",
        "clause": "9.4.7",
        "figure": "Figure 73",
        "title": "General Purpose Control (GPC) message",
        "msg_type": 5,
        "length": 8,
        "min_q": 0,
        "max_q": None,
        "brief": False,
        "pad_mode": "none",
        "fixed_only": False,
        "fields": [
            {
                "name": "gpc_msg_id",
                "offset": 2,
                "length": 6,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "eui48",
                "hex": False,
                "test_value": (0x0, 0x1C, 0xAB, 0x12, 0x34, 0x56),
                "doc": "identifier of the GPC message type",
            },
        ],
    },
    {
        "name": "serial",
        "Name": "Serial",
        "clause": "9.4.8",
        "figure": "Figure 74",
        "title": "Serial (SERIAL) message",
        "msg_type": 6,
        "length": 4,
        "min_q": 0,
        "max_q": None,
        "brief": False,
        "pad_mode": "field",
        "fixed_only": False,
        "fields": [
            {
                "name": "pad",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0xC000,
                "shift": 0xE,
                "ctype": "u8",
                "hex": False,
                "test_value": 2,
                "doc": "padding octets at the end of the payload (0 to 3)",
            },
            {
                "name": "dcd",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 0x20,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "data carrier detect",
            },
            {
                "name": "dtr",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 0x10,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "data terminal ready",
            },
            {
                "name": "dsr",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 8,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "data set ready",
            },
            {
                "name": "rts",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 4,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "request to send",
            },
            {
                "name": "cts",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 2,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "clear to send",
            },
            {
                "name": "ri",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 1,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "ring indicator",
            },
        ],
    },
    {
        "name": "parallel",
        "Name": "Parallel",
        "clause": "9.4.9",
        "figure": "Figure 75",
        "title": "Parallel (PARALLEL) message",
        "msg_type": 7,
        "length": 4,
        "min_q": 1,
        "max_q": 8,
        "brief": False,
        "pad_mode": "custom",
        "fixed_only": False,
        "fields": [
            {
                "name": "bit_width",
                "offset": 3,
                "length": 1,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u8",
                "hex": False,
                "test_value": 0x25,
                "doc": "number of valid bits in the payload starting at bit 0 (0 means 256)",
            },
        ],
    },
    {
        "name": "sensor",
        "Name": "Sensor",
        "clause": "9.4.10",
        "figure": "Figure 77",
        "title": "Sensor or Actuator (SENSOR) message",
        "msg_type": 8,
        "length": 0xC,
        "min_q": 1,
        "max_q": 0x80,
        "brief": False,
        "pad_mode": "custom",
        "fixed_only": False,
        "fields": [
            {
                "name": "mtv",
                "offset": 2,
                "length": 1,
                "kind": "bool",
                "mask": 0x80,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "message_timestamp valid",
            },
            {
                "name": "num_sensors",
                "offset": 2,
                "length": 1,
                "kind": "uint",
                "mask": 0x7F,
                "shift": 0,
                "ctype": "u8",
                "hex": False,
                "test_value": 5,
                "doc": "number of values (0 means 128)",
            },
            {
                "name": "sz",
                "offset": 3,
                "length": 1,
                "kind": "uint",
                "mask": 0xC0,
                "shift": 6,
                "ctype": "u8",
                "hex": False,
                "test_value": 1,
                "doc": "octets per value (0 means 4)",
            },
            {
                "name": "sensor_group",
                "offset": 3,
                "length": 1,
                "kind": "uint",
                "mask": 0x3F,
                "shift": 0,
                "ctype": "u8",
                "hex": False,
                "test_value": 0x2A,
                "doc": "application-specific group of sensors or actuators",
            },
            {
                "name": "message_timestamp",
                "offset": 4,
                "length": 8,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u64",
                "hex": False,
                "test_value": 0x102030405060708,
                "doc": "acquisition time in ns (9.4.1.5)",
            },
        ],
    },
    {
        "name": "sensor_brief",
        "Name": "SensorBrief",
        "clause": "9.4.11",
        "figure": "Figure 80",
        "title": "Abbreviated Sensor or Actuator (SENSOR_BRIEF) message",
        "msg_type": 9,
        "length": 4,
        "min_q": 1,
        "max_q": 0x80,
        "brief": True,
        "pad_mode": "custom",
        "fixed_only": False,
        "fields": [
            {
                "name": "mtv",
                "offset": 2,
                "length": 1,
                "kind": "bool",
                "mask": 0x80,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "message_timestamp valid - always zero on a brief message (9.4.11.1)",
            },
            {
                "name": "num_sensors",
                "offset": 2,
                "length": 1,
                "kind": "uint",
                "mask": 0x7F,
                "shift": 0,
                "ctype": "u8",
                "hex": False,
                "test_value": 5,
                "doc": "number of values (0 means 128)",
            },
            {
                "name": "sz",
                "offset": 3,
                "length": 1,
                "kind": "uint",
                "mask": 0xC0,
                "shift": 6,
                "ctype": "u8",
                "hex": False,
                "test_value": 1,
                "doc": "octets per value (0 means 4)",
            },
            {
                "name": "sensor_group",
                "offset": 3,
                "length": 1,
                "kind": "uint",
                "mask": 0x3F,
                "shift": 0,
                "ctype": "u8",
                "hex": False,
                "test_value": 0x2A,
                "doc": "application-specific group of sensors or actuators",
            },
        ],
    },
    {
        "name": "aecp",
        "Name": "Aecp",
        "clause": "9.4.12",
        "figure": "Figure 81",
        "title": "AECP message",
        "msg_type": 0xA,
        "length": 4,
        "min_q": 0,
        "max_q": None,
        "brief": False,
        "pad_mode": "none",
        "fixed_only": False,
        "fields": [],
    },
    {
        "name": "ancillary",
        "Name": "Ancillary",
        "clause": "9.4.13",
        "figure": "Figure 82",
        "title": "Ancillary Data (ANC) message",
        "msg_type": 0xB,
        "length": 8,
        "min_q": 0,
        "max_q": None,
        "brief": False,
        "pad_mode": "field",
        "fixed_only": False,
        "fields": [
            {
                "name": "pad",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0xC000,
                "shift": 0xE,
                "ctype": "u8",
                "hex": False,
                "test_value": 2,
                "doc": "padding octets at the end of the payload (0 to 3)",
            },
            {
                "name": "mode",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0xC,
                "shift": 2,
                "ctype": "u8",
                "hex": False,
                "test_value": 1,
                "doc": "payload word format (Table 26: AcfAncMode::anc_8bit / anc_10bit)",
            },
            {
                "name": "fp",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 2,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "first packet of the ancillary data stream",
            },
            {
                "name": "lp",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 1,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "last packet of the ancillary data stream",
            },
            {
                "name": "line_number",
                "offset": 4,
                "length": 2,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u16",
                "hex": False,
                "test_value": 0x2A5,
                "doc": "video line carrying the packet (progressive numbering)",
            },
            {
                "name": "did",
                "offset": 6,
                "length": 1,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u8",
                "hex": True,
                "test_value": 0x61,
                "doc": "the packet's DID",
            },
            {
                "name": "sdid_dbn",
                "offset": 7,
                "length": 1,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u8",
                "hex": True,
                "test_value": 2,
                "doc": "the packet's SDID (type 2) or DBN (type 1)",
            },
        ],
    },
    {
        "name": "byte_bus",
        "Name": "ByteBus",
        "clause": "9.4.14",
        "figure": "Figure 84",
        "title": "Generic Byte Bus (GBB) message",
        "msg_type": 0xD,
        "length": 0x10,
        "min_q": 0,
        "max_q": None,
        "brief": False,
        "pad_mode": "field",
        "fixed_only": False,
        "fields": [
            {
                "name": "pad",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0xC000,
                "shift": 0xE,
                "ctype": "u8",
                "hex": False,
                "test_value": 1,
                "doc": "padding octets at the end of the payload (0 to 3; zero when ms is set)",
            },
            {
                "name": "mtv",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 0x2000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "message_timestamp valid",
            },
            {
                "name": "byte_bus_id",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0x7FF,
                "shift": 0,
                "ctype": "u16",
                "hex": False,
                "test_value": 0x3C5,
                "doc": "target byte bus, 11 bits (application specific, Annex L and O)",
            },
            {
                "name": "message_timestamp",
                "offset": 4,
                "length": 8,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u64",
                "hex": False,
                "test_value": 0x102030405060708,
                "doc": "acquisition time in ns (9.4.1.5)",
            },
            {
                "name": "evt",
                "offset": 12,
                "length": 2,
                "kind": "uint",
                "mask": 0xF000,
                "shift": 0xC,
                "ctype": "u8",
                "hex": False,
                "test_value": 0xA,
                "doc": "upper-layer event bits (Annex G)",
            },
            {
                "name": "hs",
                "offset": 12,
                "length": 2,
                "kind": "bool",
                "mask": 0x200,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "hold stop: do not end the payload with the bus's stop indication",
            },
            {
                "name": "cs",
                "offset": 12,
                "length": 2,
                "kind": "bool",
                "mask": 0x100,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "conditional start: send only if the chain so far had no error",
            },
            {
                "name": "transaction_num",
                "offset": 12,
                "length": 2,
                "kind": "uint",
                "mask": 0xFF,
                "shift": 0,
                "ctype": "u8",
                "hex": True,
                "test_value": 0x5C,
                "doc": "request sequence number; responses echo it",
            },
            {
                "name": "op",
                "offset": 14,
                "length": 2,
                "kind": "bool",
                "mask": 0x8000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "operation: write when set, read when clear",
            },
            {
                "name": "rsp",
                "offset": 14,
                "length": 2,
                "kind": "bool",
                "mask": 0x4000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "response when set, request when clear",
            },
            {
                "name": "err",
                "offset": 14,
                "length": 2,
                "kind": "bool",
                "mask": 0x2000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "error on the associated request (responses only)",
            },
            {
                "name": "ms",
                "offset": 14,
                "length": 2,
                "kind": "bool",
                "mask": 0x1000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "more segments follow in later AVTPDUs",
            },
            {
                "name": "read_size_segment_num",
                "offset": 14,
                "length": 2,
                "kind": "uint",
                "mask": 0xFFF,
                "shift": 0,
                "ctype": "u16",
                "hex": True,
                "test_value": 0x9AB,
                "doc": "read_size on read requests, segment_num on read responses and write requests (9.4.14.14)",
            },
        ],
    },
    {
        "name": "byte_bus_brief",
        "Name": "ByteBusBrief",
        "clause": "9.4.15",
        "figure": "Figure 85",
        "title": "Abbreviated Byte Bus (ABB) message",
        "msg_type": 0xE,
        "length": 8,
        "min_q": 0,
        "max_q": None,
        "brief": True,
        "pad_mode": "field",
        "fixed_only": False,
        "fields": [
            {
                "name": "pad",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0xC000,
                "shift": 0xE,
                "ctype": "u8",
                "hex": False,
                "test_value": 1,
                "doc": "padding octets at the end of the payload (0 to 3; zero when ms is set)",
            },
            {
                "name": "mtv",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 0x2000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "message_timestamp valid - always zero on a brief message (9.4.15.2)",
            },
            {
                "name": "byte_bus_id",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0x7FF,
                "shift": 0,
                "ctype": "u16",
                "hex": False,
                "test_value": 0x3C5,
                "doc": "target byte bus, 11 bits (application specific, Annex L and O)",
            },
            {
                "name": "evt",
                "offset": 4,
                "length": 2,
                "kind": "uint",
                "mask": 0xF000,
                "shift": 0xC,
                "ctype": "u8",
                "hex": False,
                "test_value": 0xA,
                "doc": "upper-layer event bits (Annex G)",
            },
            {
                "name": "hs",
                "offset": 4,
                "length": 2,
                "kind": "bool",
                "mask": 0x200,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "hold stop: do not end the payload with the bus's stop indication",
            },
            {
                "name": "cs",
                "offset": 4,
                "length": 2,
                "kind": "bool",
                "mask": 0x100,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "conditional start: send only if the chain so far had no error",
            },
            {
                "name": "transaction_num",
                "offset": 4,
                "length": 2,
                "kind": "uint",
                "mask": 0xFF,
                "shift": 0,
                "ctype": "u8",
                "hex": True,
                "test_value": 0x5C,
                "doc": "request sequence number; responses echo it",
            },
            {
                "name": "op",
                "offset": 6,
                "length": 2,
                "kind": "bool",
                "mask": 0x8000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "operation: write when set, read when clear",
            },
            {
                "name": "rsp",
                "offset": 6,
                "length": 2,
                "kind": "bool",
                "mask": 0x4000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "response when set, request when clear",
            },
            {
                "name": "err",
                "offset": 6,
                "length": 2,
                "kind": "bool",
                "mask": 0x2000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "error on the associated request (responses only)",
            },
            {
                "name": "ms",
                "offset": 6,
                "length": 2,
                "kind": "bool",
                "mask": 0x1000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "more segments follow in later AVTPDUs",
            },
            {
                "name": "read_size_segment_num",
                "offset": 6,
                "length": 2,
                "kind": "uint",
                "mask": 0xFFF,
                "shift": 0,
                "ctype": "u16",
                "hex": True,
                "test_value": 0x9AB,
                "doc": "read_size on read requests, segment_num on read responses and write requests (9.4.14.14)",
            },
        ],
    },
    {
        "name": "i2c",
        "Name": "I2c",
        "clause": "9.4.16",
        "figure": "Figure 89",
        "title": "I2C message",
        "msg_type": 0xF,
        "length": 0x10,
        "min_q": 0,
        "max_q": 0,
        "brief": False,
        "pad_mode": "none",
        "fixed_only": True,
        "fields": [
            {
                "name": "pad_bits",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0xC000,
                "shift": 0xE,
                "ctype": "u8",
                "hex": False,
                "test_value": 0,
                "doc": "the pad field - transmitted zero and ignored on receipt (9.4.16.2); the message has no payload to pad",
            },
            {
                "name": "mtv",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 0x2000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "message_timestamp valid",
            },
            {
                "name": "i2c_bus_id",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0x7FF,
                "shift": 0,
                "ctype": "u16",
                "hex": False,
                "test_value": 0x2F1,
                "doc": "I2C bus, 11 bits (application specific, Annex L)",
            },
            {
                "name": "message_timestamp",
                "offset": 4,
                "length": 8,
                "kind": "whole",
                "mask": None,
                "shift": None,
                "ctype": "u64",
                "hex": False,
                "test_value": 0x102030405060708,
                "doc": "acquisition time in ns (9.4.1.5)",
            },
            {
                "name": "i2c_code",
                "offset": 12,
                "length": 2,
                "kind": "uint",
                "mask": 0xF000,
                "shift": 0xC,
                "ctype": "u8",
                "hex": False,
                "test_value": 4,
                "doc": "bus event (AcfI2cCode: Table 27 requests 0-7, Table 28 responses 8-12)",
            },
            {
                "name": "trr",
                "offset": 12,
                "length": 2,
                "kind": "bool",
                "mask": 0x800,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "target response request: answer a CR4/CR7 end request with TR5",
            },
            {
                "name": "transaction_num",
                "offset": 12,
                "length": 2,
                "kind": "uint",
                "mask": 0xFF,
                "shift": 0,
                "ctype": "u8",
                "hex": True,
                "test_value": 0x33,
                "doc": "request sequence number per bus; responses echo it",
            },
            {
                "name": "evt",
                "offset": 14,
                "length": 2,
                "kind": "uint",
                "mask": 0xF000,
                "shift": 0xC,
                "ctype": "u8",
                "hex": False,
                "test_value": 5,
                "doc": "upper-layer event bits (Annex G)",
            },
            {
                "name": "exception_code",
                "offset": 14,
                "length": 2,
                "kind": "uint",
                "mask": 0xF00,
                "shift": 8,
                "ctype": "u8",
                "hex": False,
                "test_value": 9,
                "doc": "response exception (AcfI2cException, Table 29)",
            },
            {
                "name": "i2c_data",
                "offset": 14,
                "length": 2,
                "kind": "uint",
                "mask": 0xFF,
                "shift": 0,
                "ctype": "u8",
                "hex": True,
                "test_value": 0xA3,
                "doc": "the event's data byte: <addr,rw> for starts (address in bits 7:1, read = 1 in bit 0), data otherwise",
            },
        ],
    },
    {
        "name": "i2c_brief",
        "Name": "I2cBrief",
        "clause": "9.4.17",
        "figure": "Figure 91",
        "title": "Abbreviated I2C message",
        "msg_type": 0x10,
        "length": 8,
        "min_q": 0,
        "max_q": 0,
        "brief": True,
        "pad_mode": "none",
        "fixed_only": True,
        "fields": [
            {
                "name": "pad_bits",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0xC000,
                "shift": 0xE,
                "ctype": "u8",
                "hex": False,
                "test_value": 0,
                "doc": "the pad field - transmitted zero and ignored on receipt (9.4.16.2); the message has no payload to pad",
            },
            {
                "name": "mtv",
                "offset": 2,
                "length": 2,
                "kind": "bool",
                "mask": 0x2000,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 0,
                "doc": "message_timestamp valid - always zero on a brief message (9.4.17.2)",
            },
            {
                "name": "i2c_bus_id",
                "offset": 2,
                "length": 2,
                "kind": "uint",
                "mask": 0x7FF,
                "shift": 0,
                "ctype": "u16",
                "hex": False,
                "test_value": 0x2F1,
                "doc": "I2C bus, 11 bits (application specific, Annex L)",
            },
            {
                "name": "i2c_code",
                "offset": 4,
                "length": 2,
                "kind": "uint",
                "mask": 0xF000,
                "shift": 0xC,
                "ctype": "u8",
                "hex": False,
                "test_value": 4,
                "doc": "bus event (AcfI2cCode: Table 27 requests 0-7, Table 28 responses 8-12)",
            },
            {
                "name": "trr",
                "offset": 4,
                "length": 2,
                "kind": "bool",
                "mask": 0x800,
                "shift": 0,
                "ctype": None,
                "hex": False,
                "test_value": 1,
                "doc": "target response request: answer a CR4/CR7 end request with TR5",
            },
            {
                "name": "transaction_num",
                "offset": 4,
                "length": 2,
                "kind": "uint",
                "mask": 0xFF,
                "shift": 0,
                "ctype": "u8",
                "hex": True,
                "test_value": 0x33,
                "doc": "request sequence number per bus; responses echo it",
            },
            {
                "name": "evt",
                "offset": 6,
                "length": 2,
                "kind": "uint",
                "mask": 0xF000,
                "shift": 0xC,
                "ctype": "u8",
                "hex": False,
                "test_value": 5,
                "doc": "upper-layer event bits (Annex G)",
            },
            {
                "name": "exception_code",
                "offset": 6,
                "length": 2,
                "kind": "uint",
                "mask": 0xF00,
                "shift": 8,
                "ctype": "u8",
                "hex": False,
                "test_value": 9,
                "doc": "response exception (AcfI2cException, Table 29)",
            },
            {
                "name": "i2c_data",
                "offset": 6,
                "length": 2,
                "kind": "uint",
                "mask": 0xFF,
                "shift": 0,
                "ctype": "u8",
                "hex": True,
                "test_value": 0xA3,
                "doc": "the event's data byte: <addr,rw> for starts (address in bits 7:1, read = 1 in bit 0), data otherwise",
            },
        ],
    },
]

ACF_MSG_TYPE_NAMES: dict[int, str] = {
    0x00: "ACF_FLEXRAY",
    0x01: "ACF_CAN",
    0x02: "ACF_CAN_BRIEF",
    0x03: "ACF_LIN",
    0x04: "ACF_MOST",
    0x05: "ACF_GPC",
    0x06: "ACF_SERIAL",
    0x07: "ACF_PARALLEL",
    0x08: "ACF_SENSOR",
    0x09: "ACF_SENSOR_BRIEF",
    0x0A: "ACF_AECP",
    0x0B: "ACF_ANCILLARY",
    0x0C: "ACF_GISF",
    0x0D: "ACF_BYTE_BUS",
    0x0E: "ACF_BYTE_BUS_BRIEF",
    0x0F: "ACF_I2C",
    0x10: "ACF_I2C_BRIEF",
    0x11: "ACF_CAN_XL",
    0x12: "ACF_CAN_XL_BRIEF",
    0x21: "ACF_CAN_V2",
    0x22: "ACF_CAN_BRIEF_V2",
    0x23: "ACF_LIN_V2",
    0x76: "ACF_CHECKSUM",
    0x77: "ACF_CRC",
}

ACF_CRC_TYPE_NAMES: dict[int, str] = {0x0: "CRC_ETH", 0x1: "CRC_32P4", 0xF: "CRC_USER"}
