# Copyright 2026 Jeff Koftinoff <jeff.koftinoff@statusbar.com>
# SPDX-License-Identifier: MIT
"""Emit the generated Lua field tables from the layouts.

The output is a Lua module with no side effects beyond defining tables: the
``ProtoField`` objects, the value-name tables, the header-kind table and one
``add_<layout>(tree, tvb, off)`` function per layout that adds every field of
the layout to a tree at a byte offset. Field abbreviations are unique across
layouts; a field reused by several layouts is emitted once and its definition
must be identical everywhere (checked).
"""

from __future__ import annotations

from . import layouts as L

GPL_HEADER = """\
-- SPDX-License-Identifier: GPL-2.0-or-later
-- Copyright 2026 Jeff Koftinoff <jeff.koftinoff@statusbar.com>
--
-- GENERATED by python/wireshark_schema (luagen.py) from layouts.py - do not
-- edit; regenerate with: python3 -m wireshark_schema gen-lua wireshark
-- The schema is MIT; this emitted file is distributed under the GPL with the
-- rest of the wireshark/ directory because it uses the Wireshark Lua API.
--
-- Wireshark 4.x executes every .lua file it finds under a plugin folder,
-- including this module, passing it (basename, path); only a require() from
-- the loader statusbar_avb.lua, which passes the dotted module name, may run it.
if type((...)) ~= "string" or not (...):find("^statusbar_avb%.") then
    return
end
"""

_PROTOFIELD = {
    "u8": "ProtoField.uint8",
    "u16": "ProtoField.uint16",
    "u24": "ProtoField.uint24",
    "u32": "ProtoField.uint32",
    "u64": "ProtoField.uint64",
    "i8": "ProtoField.int8",
    "i16": "ProtoField.int16",
    "i24": "ProtoField.int24",
    "i32": "ProtoField.int32",
    "i64": "ProtoField.int64",
    "f32": "ProtoField.float",
    "f64": "ProtoField.double",
    "bool": "ProtoField.bool",
    "bytes": "ProtoField.bytes",
    "eui48": "ProtoField.ether",
    "string": "ProtoField.string",
}


def _lua_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _value_table_name(name: str) -> str:
    return f"M.values_{name}"


def _protofield(layout: L.Layout, f: L.Field) -> str:
    abbr = _lua_string(layout.abbr(f))
    title = _lua_string(f.name)
    ctor = _PROTOFIELD[f.kind]
    mask = f"0x{f.mask:X}" if f.mask is not None else "nil"
    if f.kind == "bool":
        # A flag inside an integer shows that integer's width; a standalone
        # boolean (no mask) must use base.NONE per the Wireshark Lua API.
        display = f"{max(f.length, 1) * 8}" if f.mask is not None else "base.NONE"
        return f"{ctor}({abbr}, {title}, {display}, nil, {mask}, {_lua_string(f.doc)})"
    if f.kind in ("bytes", "eui48"):
        return f"{ctor}({abbr}, {title}, base.NONE, {_lua_string(f.doc)})"
    if f.kind == "string":
        return f"{ctor}({abbr}, {title}, base.ASCII, {_lua_string(f.doc)})"
    if f.kind in ("f32", "f64"):
        return f"{ctor}({abbr}, {title}, nil, {_lua_string(f.doc)})"
    base = "base.HEX" if f.base == "hex" else "base.DEC"
    values = _value_table_name(f.values) if f.values else "nil"
    return f"{ctor}({abbr}, {title}, {base}, {values}, {mask}, {_lua_string(f.doc)})"


def _field_key(layout: L.Layout, f: L.Field) -> str:
    """The key under M.f: the abbreviation with its prefix dropped."""
    return layout.abbr(f)[len("avb.") :].replace(".", "_")


def generate_avtp_fields() -> str:
    """The gen/avtp_fields.lua module."""
    out: list[str] = [GPL_HEADER, "local M = {}", ""]

    for vt in L.VALUE_TABLES.values():
        out.append(f"{_value_table_name(vt.name)} = {{")
        for code, name in sorted(vt.entries.items()):
            out.append(f"    [0x{code:02X}] = {_lua_string(name)},")
        out += ["}", ""]

    out.append("M.subtype_names = M.values_avtp_subtype")
    out.append("")
    out.append("M.header_kind = {")
    for code, kind in sorted(L.HEADER_KIND.items()):
        out.append(f"    [0x{code:02X}] = {_lua_string(kind)},")
    out += ["}", ""]

    # Unique fields across layouts, definition checked for consistency.
    defs: dict[str, str] = {}
    order: list[str] = []
    for layout in L.AVTP_LAYOUTS + L.SUBTYPE_LAYOUTS + (L.IP_AVTPDU,):
        for f in layout.fields:
            key = _field_key(layout, f)
            text = _protofield(layout, f)
            if key in defs and defs[key] != text:
                raise ValueError(
                    f"field {layout.abbr(f)} defined differently in {layout.name}"
                )
            if key not in defs:
                defs[key] = text
                order.append(key)
    payload_key = "avtp_payload"
    defs[payload_key] = _protofield(L.AVTP_COMMON, L.PAYLOAD)
    order.append(payload_key)
    for layout in L.EXTRA_FIELD_LAYOUTS:
        for f in layout.fields:
            key = _field_key(layout, f)
            if key not in defs:
                defs[key] = _protofield(layout, f)
                order.append(key)

    out.append("M.f = {}")
    for key in order:
        out.append(f"M.f.{key} = {defs[key]}")
    out.append("")
    out.append("M.avtp_fields = {")
    for key in order:
        if not key.startswith("ipavtp_"):
            out.append(f"    M.f.{key},")
    out += ["}", ""]
    out.append("M.ipavtp_fields = {")
    for key in order:
        if key.startswith("ipavtp_"):
            out.append(f"    M.f.{key},")
    out += ["}", ""]

    for layout in L.AVTP_LAYOUTS + L.SUBTYPE_LAYOUTS + (L.IP_AVTPDU,):
        out.append(f"--- {layout.doc}")
        fname = "add_ip_avtpdu" if layout is L.IP_AVTPDU else f"add_{layout.name}"
        out.append(f"function M.{fname}(tree, tvb, off)")
        for f in layout.fields:
            out.append(
                f"    tree:add(M.f.{_field_key(layout, f)}, tvb(off + {f.offset}, {f.length}))"
            )
        out += ["end", ""]

    # Per-(subtype, version) specs: which add_ functions, where the payload
    # starts, and the post hook (implemented in the hand-written module).
    out.append(
        "--- (subtype, version) -> { header_length, layouts = { add fns }, post = name|nil }"
    )
    out.append("M.subtype_specs = {}")
    for spec in L.SUBTYPE_SPECS:
        adds = ", ".join(f"M.add_{layout.name}" for layout in spec.layouts)
        post = _lua_string(spec.post) if spec.post else "nil"
        out.append(
            f"M.subtype_specs[0x{spec.subtype:02X}] = M.subtype_specs[0x{spec.subtype:02X}] or {{}}"
        )
        out.append(
            f"M.subtype_specs[0x{spec.subtype:02X}][{spec.version}] = "
            f"{{ name = {_lua_string(spec.name)}, header_length = {spec.header_length}, "
            f"layouts = {{ {adds} }}, post = {post} }}"
        )
    out.append("")
    out.append("return M")
    return "\n".join(out) + "\n"


def generate_acf_fields() -> str:
    """The gen/acf_fields.lua module: ACF header, every type, the trailers, specs."""
    out: list[str] = [GPL_HEADER, "local M = {}", ""]
    for name in ("acf_msg_type", "acf_crc_type"):
        vt = L.VALUE_TABLES[name]
        out.append(f"{_value_table_name(vt.name)} = {{")
        for code, title in sorted(vt.entries.items()):
            out.append(f"    [0x{code:02X}] = {_lua_string(title)},")
        out += ["}", ""]

    defs: dict[str, str] = {}
    order: list[str] = []
    for layout in L.ACF_LAYOUTS:
        for f in layout.fields:
            key = _field_key(layout, f)
            text = _protofield(layout, f)
            if key in defs and defs[key] != text:
                raise ValueError(
                    f"field {layout.abbr(f)} defined differently in {layout.name}"
                )
            if key not in defs:
                defs[key] = text
                order.append(key)
    out.append("M.f = {}")
    for key in order:
        out.append(f"M.f.{key} = {defs[key]}")
    out += ["", "M.acf_fields = {"]
    for key in order:
        out.append(f"    M.f.{key},")
    out += ["}", ""]

    for layout in L.ACF_LAYOUTS:
        out.append(f"--- {layout.doc}")
        out.append(f"function M.add_{layout.name}(tree, tvb, off)")
        for f in layout.fields:
            if f.length == 0:
                continue
            out.append(
                f"    tree:add(M.f.{_field_key(layout, f)}, tvb(off + {f.offset}, {f.length}))"
            )
        out += ["end", ""]

    out.append(
        "--- msg_type -> { name, length, add, pad_mode, fixed_only, brief, min_q, max_q, payload }"
    )
    out.append("M.specs = {}")
    for msg_type, spec in sorted(L.ACF_SPECS.items()):
        max_q = "nil" if spec.max_q is None else str(spec.max_q)
        payload_key = (
            _field_key(spec.layout, L.Field("payload", 0, 0, "bytes"))
            if not spec.fixed_only
            else None
        )
        payload = f"M.f.{payload_key}" if payload_key else "nil"
        out.append(
            f"M.specs[0x{msg_type:02X}] = {{ name = {_lua_string(spec.name)}, length = {spec.length}, "
            f"add = M.add_{spec.layout.name}, pad_mode = {_lua_string(spec.pad_mode)}, "
            f"fixed_only = {'true' if spec.fixed_only else 'false'}, brief = {'true' if spec.brief else 'false'}, "
            f"min_q = {spec.min_q}, max_q = {max_q}, payload = {payload} }}"
        )
    out += [
        "",
        f"M.MSG_TYPE_CHECKSUM = 0x{L.ACF_MSG_TYPE_CHECKSUM:02X}",
        f"M.MSG_TYPE_CRC = 0x{L.ACF_MSG_TYPE_CRC:02X}",
        "",
        "return M",
    ]
    return "\n".join(out) + "\n"


def _emit_fields_and_adds(
    out: list[str], layouts: tuple, placeholders: list[tuple] = ()
) -> list[str]:
    """Emit M.f entries, the fields list and add_<layout>() for `layouts`; returns the field keys."""
    defs: dict[str, str] = {}
    order: list[str] = []
    for layout in layouts:
        for f in layout.fields:
            key = _field_key(layout, f)
            text = _protofield(layout, f)
            if key in defs and defs[key] != text:
                raise ValueError(
                    f"field {layout.abbr(f)} defined differently in {layout.name}"
                )
            if key not in defs:
                defs[key] = text
                order.append(key)
    for layout, f in placeholders:
        key = _field_key(layout, f)
        if key not in defs:
            defs[key] = _protofield(layout, f)
            order.append(key)
    out.append("M.f = {}")
    for key in order:
        out.append(f"M.f.{key} = {defs[key]}")
    out += ["", "M.fields = {"]
    for key in order:
        out.append(f"    M.f.{key},")
    out += ["}", ""]
    for layout in layouts:
        out.append(f"--- {layout.doc}")
        out.append(f"function M.add_{layout.name.replace('.', '_')}(tree, tvb, off)")
        for f in layout.fields:
            if f.length == 0:
                continue
            if f.repeat > 1:
                out.append(f"    for i = 0, {f.repeat - 1} do")
                out.append(
                    f"        tree:add(M.f.{_field_key(layout, f)}, tvb(off + {f.offset} + (i * {f.length}), {f.length}))"
                )
                out.append("    end")
                continue
            out.append(
                f"    tree:add(M.f.{_field_key(layout, f)}, tvb(off + {f.offset}, {f.length}))"
            )
        out += ["end", ""]
    return order


def generate_atdecc_fields() -> str:
    """The gen/atdecc_fields.lua module: ADP, ACMP, AECP, AEM payloads, descriptors,
    control values, stream formats, MVU and AVC."""
    from . import atdecc_layouts as A
    from . import atdecc_std as STD
    from . import atdecc_table as TA

    out: list[str] = [GPL_HEADER, "local M = {}", ""]
    for name in (
        "aem_command",
        "descriptor_type",
        "aem_status",
        "aecp_message_type",
        "acmp_message_type",
        "acmp_status",
        "adp_message_type",
        "aa_mode",
        "aa_status",
        "jdks_log_priority",
        "control_value_type",
        "control_unit_code",
        "mvu_command",
        "mvu_status",
        # referenced by the stream-format sub-fields
        "aaf_nsr",
        "aaf_format",
        "crf_type",
        "crf_pull",
        "am824_fdf",
        "am824_label",
    ):
        vt = L.VALUE_TABLES[name]
        out.append(f"{_value_table_name(vt.name)} = {{")
        for code, title in sorted(vt.entries.items()):
            out.append(f"    [0x{code:02X}] = {_lua_string(title)},")
        out += ["}", ""]
    placeholders = [
        (A.AEM, A.AEM_PAYLOAD_RAW),
        (A.DESCRIPTOR_LAYOUTS["DescriptorControl"], A.DESCRIPTOR_RAW),
        (A.JDKS_LOG, A.JDKS_LOG_TEXT),
        (A.AVC, A.AVC_PAYLOAD),
        (A.CONTROL_VALUE, A.CONTROL_UTF8),
        (A.CONTROL_VALUE, A.CONTROL_VENDOR),
    ]
    for layout in A.MVU_PAYLOAD_LAYOUTS.values():
        for f in layout.fields:
            if f.length == 0:
                placeholders.append((layout, f))
    _emit_fields_and_adds(out, A.ATDECC_LAYOUTS, placeholders)

    def fkey(layout, f):
        return f"M.f.{_field_key(layout, f)}"

    def addname(layout):
        return f"M.add_{layout.name.replace('.', '_')}"

    out.append("M.AEM_PAYLOAD_RAW = " + fkey(A.AEM, A.AEM_PAYLOAD_RAW))
    out.append("M.AECP_PAYLOAD = " + fkey(A.AECP, A.AECP_PAYLOAD))
    out.append("M.AA_TLV_DATA = " + fkey(A.AA_TLV, A.AA_TLV_DATA))
    out.append("M.VU_PAYLOAD = " + fkey(A.VU, A.VU_PAYLOAD))
    out.append("M.AVC_PAYLOAD = " + fkey(A.AVC, A.AVC_PAYLOAD))
    out.append("M.CONTROL_UTF8 = " + fkey(A.CONTROL_VALUE, A.CONTROL_UTF8))
    out.append("M.CONTROL_VENDOR = " + fkey(A.CONTROL_VALUE, A.CONTROL_VENDOR))
    out.append(
        "M.DESCRIPTOR_RAW = "
        + fkey(A.DESCRIPTOR_LAYOUTS["DescriptorControl"], A.DESCRIPTOR_RAW)
    )
    out.append("M.JDKS_LOG_TEXT = " + fkey(A.JDKS_LOG, A.JDKS_LOG_TEXT))
    out.append("")

    def trailer_table(trailer, struct_members):
        if trailer is None:
            return "nil"
        if trailer.kind != "elements":
            return f"{{ kind = {_lua_string(trailer.kind)} }}"
        count_off = struct_members[trailer.count_field]["offset"]
        return (
            f'{{ kind = "elements", element = {_lua_string(trailer.element)}, '
            f"element_size = {A.ELEMENT_SIZE[trailer.element]}, element_add = {addname(A.TRAILER_ELEMENTS[trailer.element])}, "
            f"count_field_offset = {A.AEM_HEADER_LENGTH + count_off} }}"
        )

    out.append(
        "--- command code -> { cmd = spec, rsp = spec }; spec = { name, length, add, trailer = nil | { kind, ... } }"
    )
    out.append("M.aem_payloads = {}")
    for code, (cmd, rsp) in sorted(A.AEM_PAYLOADS.items()):

        def spec(p):
            if p is None:
                return "nil"
            members = {m["name"]: m for m in A.ALL_PAYLOAD_STRUCTS[p.struct]["members"]}
            return (
                f"{{ name = {_lua_string(p.name)}, length = {p.length}, add = {addname(p.layout)}, "
                f"trailer = {trailer_table(p.trailer, members)} }}"
            )

        out.append(
            f"M.aem_payloads[0x{code:04X}] = {{ cmd = {spec(cmd)}, rsp = {spec(rsp)} }}"
        )
    out.append("")
    out.append(
        "--- descriptor type -> { name, length, add, tables = { { count_field_offset|nil, offset_field_offset, element, element_size, element_add|nil, value_type_offset|nil } } }"
    )
    out.append("M.descriptors = {}")
    for code, d in sorted(A.DESCRIPTORS.items()):
        members = {m["name"]: m for m in TA.DESCRIPTOR_STRUCTS[d.struct]["members"]}
        tables = []
        for t in d.trailers:
            count_off = (
                str(members[t.count_field]["offset"]) if t.count_field else "nil"
            )
            offset_off = members[t.offset_field]["offset"]
            elem_add = (
                addname(A.TRAILER_ELEMENTS[t.element])
                if t.element in A.TRAILER_ELEMENTS
                else "nil"
            )
            vt_off = (
                str(members[t.value_type_field]["offset"])
                if t.value_type_field
                else "nil"
            )
            tables.append(
                f"{{ count_field_offset = {count_off}, offset_field_offset = {offset_off}, "
                f"element = {_lua_string(t.element)}, element_size = {t.element_size}, element_add = {elem_add}, "
                f"value_type_offset = {vt_off} }}"
            )
        out.append(
            f"M.descriptors[0x{code:04X}] = {{ name = {_lua_string(d.name)}, length = {d.length}, "
            f"add = {addname(d.layout)}, tables = {{ {', '.join(tables)} }} }}"
        )
    out.append("")
    out.append(
        "--- control_value_type (14-bit) -> { family, size, field }; field is the typed per-element ProtoField"
    )
    out.append("M.control_value_family = {}")
    kind_field = {
        k: f"M.f.atdecc_control_value_{k}"
        for k in ("i8", "u8", "i16", "u16", "i32", "u32", "i64", "u64", "f32", "f64")
    }
    kind_field["string_ref"] = "M.f.atdecc_control_value_string_ref"
    for vt, (family, size, kind) in sorted(A.CONTROL_VALUE_FAMILY.items()):
        field = kind_field.get(kind, "nil") if kind else "nil"
        out.append(
            f"M.control_value_family[0x{vt:04X}] = {{ family = {_lua_string(family)}, size = {size}, field = {field} }}"
        )
    out.append("")
    out.append(
        "--- payload / descriptor spec name -> offsets of 8-octet stream formats"
    )
    out.append("M.stream_format_at = {")
    for name, offs in sorted(A.STREAM_FORMAT_AT.items()):
        out.append(f"    {name} = {{ {', '.join(str(o) for o in offs)} }},")
    out += [
        "}",
        "--- stream format subtype -> add function for its sub-fields",
        "M.stream_format_add = {",
    ]
    for subtype, layout in sorted(A.STREAM_FORMAT_LAYOUTS.items()):
        out.append(f"    [0x{subtype:02X}] = {addname(layout)},")
    out += ["}", ""]
    out.append(
        "--- MVU command_type -> { cmd = spec, rsp = spec }; spec = { name, length, add, name_field }"
    )
    out.append("M.mvu_payloads = {}")
    for code, (cmd, rsp) in sorted(A.MVU_PAYLOADS.items()):

        def mspec(p):
            if p is None:
                return "nil"
            name_field = "nil"
            if p.optional_name:
                f = next(f for f in p.layout.fields if f.name == p.optional_name)
                name_field = fkey(p.layout, f)
            return f"{{ name = {_lua_string(p.name)}, length = {p.length}, add = {addname(p.layout)}, name_field = {name_field} }}"

        out.append(
            f"M.mvu_payloads[0x{code:04X}] = {{ cmd = {mspec(cmd)}, rsp = {mspec(rsp)} }}"
        )
    out.append("M.mvu_features_flag_fields = {")
    for name, _mask in STD.MVU_FEATURES_FLAGS:
        out.append(f"    M.f.atdecc_mvu_features_flags_{name},")
    out += ["}", "M.mvu_mcr_flag_fields = {"]
    for name, _mask in STD.MVU_MCR_FLAGS:
        out.append(f"    M.f.atdecc_mvu_mcr_flags_{name},")
    out += ["}", ""]
    out.append(f"M.MVU_PROTOCOL_ID = {_lua_string(STD.MVU_PROTOCOL_ID)}")
    out.append(f"M.MVU_HEADER_LENGTH = {A.MVU_HEADER_LENGTH}")
    out.append(f"M.AVC_HEADER_LENGTH = {A.AVC_HEADER_LENGTH}")
    out.append(
        f"M.AUDIO_MAPPING_LENGTH = {TA.AEM_PAYLOAD_STRUCTS['AemAudioMapping']['length']}"
    )
    out.append(f"M.JDKS_CONTROL_LOG_TEXT = {_lua_string(TA.JDKS_CONTROL_LOG_TEXT)}")
    out.append(
        f"M.JDKS_CONTROL_IPV4_PARAMETERS = {_lua_string(TA.JDKS_CONTROL_IPV4_PARAMETERS)}"
    )
    out.append(f"M.JDKS_LOG_BLOB_LENGTH = {TA.JDKS_LOG_BLOB['length']}")
    out.append(f"M.JDKS_IPV4_PARAMS_LENGTH = {TA.JDKS_IPV4_PARAMS['length']}")
    out.append(f"M.AECP_HEADER_LENGTH = {A.AECP_HEADER_LENGTH}")
    out.append(f"M.AEM_HEADER_LENGTH = {A.AEM_HEADER_LENGTH}")
    out.append(f"M.AA_HEADER_LENGTH = {A.AA_HEADER_LENGTH}")
    out.append(f"M.VU_HEADER_LENGTH = {A.VU_HEADER_LENGTH}")
    out.append("")
    out.append("return M")
    return "\n".join(out) + "\n"
