# Copyright 2026 Jeff Koftinoff <jeff.koftinoff@statusbar.com>
# SPDX-License-Identifier: MIT
"""Emit the generated Lua field tables from the layouts.

The output is a Lua module with no side effects beyond defining tables: the
``ProtoField`` objects, the value-name tables, the header-kind table and one
``add_<layout>(tree, tvb, off)`` function per layout that adds every field of
the layout to a tree at a byte offset. Field abbreviations are unique across
layouts; a field reused by several layouts is emitted once and its definition
must be identical everywhere (checked).
"""

from __future__ import annotations

from . import layouts as L

GPL_HEADER = """\
-- SPDX-License-Identifier: GPL-2.0-or-later
-- Copyright 2026 Jeff Koftinoff <jeff.koftinoff@statusbar.com>
--
-- GENERATED by python/wireshark_schema (luagen.py) from layouts.py - do not
-- edit; regenerate with: python3 -m wireshark_schema gen-lua wireshark
-- The schema is MIT; this emitted file is distributed under the GPL with the
-- rest of the wireshark/ directory because it uses the Wireshark Lua API.
"""

_PROTOFIELD = {
    "u8": "ProtoField.uint8",
    "u16": "ProtoField.uint16",
    "u32": "ProtoField.uint32",
    "u64": "ProtoField.uint64",
    "bool": "ProtoField.bool",
    "bytes": "ProtoField.bytes",
    "eui48": "ProtoField.ether",
}


def _lua_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _value_table_name(name: str) -> str:
    return f"M.values_{name}"


def _protofield(layout: L.Layout, f: L.Field) -> str:
    abbr = _lua_string(layout.abbr(f))
    title = _lua_string(f.name)
    ctor = _PROTOFIELD[f.kind]
    mask = f"0x{f.mask:X}" if f.mask is not None else "nil"
    if f.kind == "bool":
        return f"{ctor}({abbr}, {title}, {f.length * 8}, nil, {mask}, {_lua_string(f.doc)})"
    if f.kind in ("bytes", "eui48"):
        return f"{ctor}({abbr}, {title}, base.NONE, {_lua_string(f.doc)})"
    base = "base.HEX" if f.base == "hex" else "base.DEC"
    values = _value_table_name(f.values) if f.values else "nil"
    return f"{ctor}({abbr}, {title}, {base}, {values}, {mask}, {_lua_string(f.doc)})"


def _field_key(layout: L.Layout, f: L.Field) -> str:
    """The key under M.f: the abbreviation with its prefix dropped."""
    return layout.abbr(f)[len("avb.") :].replace(".", "_")


def generate_avtp_fields() -> str:
    """The gen/avtp_fields.lua module."""
    out: list[str] = [GPL_HEADER, "local M = {}", ""]

    for vt in L.VALUE_TABLES.values():
        out.append(f"{_value_table_name(vt.name)} = {{")
        for code, name in sorted(vt.entries.items()):
            out.append(f"    [0x{code:02X}] = {_lua_string(name)},")
        out += ["}", ""]

    out.append("M.subtype_names = M.values_avtp_subtype")
    out.append("")
    out.append("M.header_kind = {")
    for code, kind in sorted(L.HEADER_KIND.items()):
        out.append(f"    [0x{code:02X}] = {_lua_string(kind)},")
    out += ["}", ""]

    # Unique fields across layouts, definition checked for consistency.
    defs: dict[str, str] = {}
    order: list[str] = []
    for layout in L.AVTP_LAYOUTS + (L.IP_AVTPDU,):
        for f in layout.fields:
            key = _field_key(layout, f)
            text = _protofield(layout, f)
            if key in defs and defs[key] != text:
                raise ValueError(
                    f"field {layout.abbr(f)} defined differently in {layout.name}"
                )
            if key not in defs:
                defs[key] = text
                order.append(key)
    payload_key = "avtp_payload"
    defs[payload_key] = _protofield(L.AVTP_COMMON, L.PAYLOAD)
    order.append(payload_key)

    out.append("M.f = {}")
    for key in order:
        out.append(f"M.f.{key} = {defs[key]}")
    out.append("")
    out.append("M.avtp_fields = {")
    for key in order:
        if not key.startswith("ipavtp_"):
            out.append(f"    M.f.{key},")
    out += ["}", ""]
    out.append("M.ipavtp_fields = {")
    for key in order:
        if key.startswith("ipavtp_"):
            out.append(f"    M.f.{key},")
    out += ["}", ""]

    for layout in L.AVTP_LAYOUTS + (L.IP_AVTPDU,):
        out.append(f"--- {layout.doc}")
        fname = "add_ip_avtpdu" if layout is L.IP_AVTPDU else f"add_{layout.name}"
        out.append(f"function M.{fname}(tree, tvb, off)")
        for f in layout.fields:
            out.append(
                f"    tree:add(M.f.{_field_key(layout, f)}, tvb(off + {f.offset}, {f.length}))"
            )
        out += ["end", ""]

    out.append("return M")
    return "\n".join(out) + "\n"
