# Copyright 2026 Jeff Koftinoff <jeff.koftinoff@statusbar.com>
# SPDX-License-Identifier: MIT
"""Emit the generated Lua field tables from the layouts.

The output is a Lua module with no side effects beyond defining tables: the
``ProtoField`` objects, the value-name tables, the header-kind table and one
``add_<layout>(tree, tvb, off)`` function per layout that adds every field of
the layout to a tree at a byte offset. Field abbreviations are unique across
layouts; a field reused by several layouts is emitted once and its definition
must be identical everywhere (checked).
"""

from __future__ import annotations

from . import layouts as L

GPL_HEADER = """\
-- SPDX-License-Identifier: GPL-2.0-or-later
-- Copyright 2026 Jeff Koftinoff <jeff.koftinoff@statusbar.com>
--
-- GENERATED by python/wireshark_schema (luagen.py) from layouts.py - do not
-- edit; regenerate with: python3 -m wireshark_schema gen-lua wireshark
-- The schema is MIT; this emitted file is distributed under the GPL with the
-- rest of the wireshark/ directory because it uses the Wireshark Lua API.
--
-- Wireshark 4.x executes every .lua file it finds under a plugin folder,
-- including this module, passing it (basename, path); only a require() from
-- the loader statusbar_avb.lua, which passes the dotted module name, may run it.
if type((...)) ~= "string" or not (...):find("^statusbar_avb%.") then
    return
end
"""

_PROTOFIELD = {
    "u8": "ProtoField.uint8",
    "u16": "ProtoField.uint16",
    "u32": "ProtoField.uint32",
    "u64": "ProtoField.uint64",
    "i16": "ProtoField.int16",
    "i24": "ProtoField.int24",
    "i32": "ProtoField.int32",
    "f32": "ProtoField.float",
    "bool": "ProtoField.bool",
    "bytes": "ProtoField.bytes",
    "eui48": "ProtoField.ether",
    "string": "ProtoField.string",
}


def _lua_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _value_table_name(name: str) -> str:
    return f"M.values_{name}"


def _protofield(layout: L.Layout, f: L.Field) -> str:
    abbr = _lua_string(layout.abbr(f))
    title = _lua_string(f.name)
    ctor = _PROTOFIELD[f.kind]
    mask = f"0x{f.mask:X}" if f.mask is not None else "nil"
    if f.kind == "bool":
        # A flag inside an integer shows that integer's width; a standalone
        # boolean (no mask) must use base.NONE per the Wireshark Lua API.
        display = f"{max(f.length, 1) * 8}" if f.mask is not None else "base.NONE"
        return f"{ctor}({abbr}, {title}, {display}, nil, {mask}, {_lua_string(f.doc)})"
    if f.kind in ("bytes", "eui48"):
        return f"{ctor}({abbr}, {title}, base.NONE, {_lua_string(f.doc)})"
    if f.kind == "string":
        return f"{ctor}({abbr}, {title}, base.ASCII, {_lua_string(f.doc)})"
    if f.kind == "f32":
        return f"{ctor}({abbr}, {title}, nil, {_lua_string(f.doc)})"
    base = "base.HEX" if f.base == "hex" else "base.DEC"
    values = _value_table_name(f.values) if f.values else "nil"
    return f"{ctor}({abbr}, {title}, {base}, {values}, {mask}, {_lua_string(f.doc)})"


def _field_key(layout: L.Layout, f: L.Field) -> str:
    """The key under M.f: the abbreviation with its prefix dropped."""
    return layout.abbr(f)[len("avb.") :].replace(".", "_")


def generate_avtp_fields() -> str:
    """The gen/avtp_fields.lua module."""
    out: list[str] = [GPL_HEADER, "local M = {}", ""]

    for vt in L.VALUE_TABLES.values():
        out.append(f"{_value_table_name(vt.name)} = {{")
        for code, name in sorted(vt.entries.items()):
            out.append(f"    [0x{code:02X}] = {_lua_string(name)},")
        out += ["}", ""]

    out.append("M.subtype_names = M.values_avtp_subtype")
    out.append("")
    out.append("M.header_kind = {")
    for code, kind in sorted(L.HEADER_KIND.items()):
        out.append(f"    [0x{code:02X}] = {_lua_string(kind)},")
    out += ["}", ""]

    # Unique fields across layouts, definition checked for consistency.
    defs: dict[str, str] = {}
    order: list[str] = []
    for layout in L.AVTP_LAYOUTS + L.SUBTYPE_LAYOUTS + (L.IP_AVTPDU,):
        for f in layout.fields:
            key = _field_key(layout, f)
            text = _protofield(layout, f)
            if key in defs and defs[key] != text:
                raise ValueError(
                    f"field {layout.abbr(f)} defined differently in {layout.name}"
                )
            if key not in defs:
                defs[key] = text
                order.append(key)
    payload_key = "avtp_payload"
    defs[payload_key] = _protofield(L.AVTP_COMMON, L.PAYLOAD)
    order.append(payload_key)
    for layout in L.EXTRA_FIELD_LAYOUTS:
        for f in layout.fields:
            key = _field_key(layout, f)
            if key not in defs:
                defs[key] = _protofield(layout, f)
                order.append(key)

    out.append("M.f = {}")
    for key in order:
        out.append(f"M.f.{key} = {defs[key]}")
    out.append("")
    out.append("M.avtp_fields = {")
    for key in order:
        if not key.startswith("ipavtp_"):
            out.append(f"    M.f.{key},")
    out += ["}", ""]
    out.append("M.ipavtp_fields = {")
    for key in order:
        if key.startswith("ipavtp_"):
            out.append(f"    M.f.{key},")
    out += ["}", ""]

    for layout in L.AVTP_LAYOUTS + L.SUBTYPE_LAYOUTS + (L.IP_AVTPDU,):
        out.append(f"--- {layout.doc}")
        fname = "add_ip_avtpdu" if layout is L.IP_AVTPDU else f"add_{layout.name}"
        out.append(f"function M.{fname}(tree, tvb, off)")
        for f in layout.fields:
            out.append(
                f"    tree:add(M.f.{_field_key(layout, f)}, tvb(off + {f.offset}, {f.length}))"
            )
        out += ["end", ""]

    # Per-(subtype, version) specs: which add_ functions, where the payload
    # starts, and the post hook (implemented in the hand-written module).
    out.append(
        "--- (subtype, version) -> { header_length, layouts = { add fns }, post = name|nil }"
    )
    out.append("M.subtype_specs = {}")
    for spec in L.SUBTYPE_SPECS:
        adds = ", ".join(f"M.add_{layout.name}" for layout in spec.layouts)
        post = _lua_string(spec.post) if spec.post else "nil"
        out.append(
            f"M.subtype_specs[0x{spec.subtype:02X}] = M.subtype_specs[0x{spec.subtype:02X}] or {{}}"
        )
        out.append(
            f"M.subtype_specs[0x{spec.subtype:02X}][{spec.version}] = "
            f"{{ name = {_lua_string(spec.name)}, header_length = {spec.header_length}, "
            f"layouts = {{ {adds} }}, post = {post} }}"
        )
    out.append("")
    out.append("return M")
    return "\n".join(out) + "\n"


def generate_acf_fields() -> str:
    """The gen/acf_fields.lua module: ACF header, every type, the trailers, specs."""
    out: list[str] = [GPL_HEADER, "local M = {}", ""]
    for name in ("acf_msg_type", "acf_crc_type"):
        vt = L.VALUE_TABLES[name]
        out.append(f"{_value_table_name(vt.name)} = {{")
        for code, title in sorted(vt.entries.items()):
            out.append(f"    [0x{code:02X}] = {_lua_string(title)},")
        out += ["}", ""]

    defs: dict[str, str] = {}
    order: list[str] = []
    for layout in L.ACF_LAYOUTS:
        for f in layout.fields:
            key = _field_key(layout, f)
            text = _protofield(layout, f)
            if key in defs and defs[key] != text:
                raise ValueError(
                    f"field {layout.abbr(f)} defined differently in {layout.name}"
                )
            if key not in defs:
                defs[key] = text
                order.append(key)
    out.append("M.f = {}")
    for key in order:
        out.append(f"M.f.{key} = {defs[key]}")
    out += ["", "M.acf_fields = {"]
    for key in order:
        out.append(f"    M.f.{key},")
    out += ["}", ""]

    for layout in L.ACF_LAYOUTS:
        out.append(f"--- {layout.doc}")
        out.append(f"function M.add_{layout.name}(tree, tvb, off)")
        for f in layout.fields:
            if f.length == 0:
                continue
            out.append(
                f"    tree:add(M.f.{_field_key(layout, f)}, tvb(off + {f.offset}, {f.length}))"
            )
        out += ["end", ""]

    out.append(
        "--- msg_type -> { name, length, add, pad_mode, fixed_only, brief, min_q, max_q, payload }"
    )
    out.append("M.specs = {}")
    for msg_type, spec in sorted(L.ACF_SPECS.items()):
        max_q = "nil" if spec.max_q is None else str(spec.max_q)
        payload_key = (
            _field_key(spec.layout, L.Field("payload", 0, 0, "bytes"))
            if not spec.fixed_only
            else None
        )
        payload = f"M.f.{payload_key}" if payload_key else "nil"
        out.append(
            f"M.specs[0x{msg_type:02X}] = {{ name = {_lua_string(spec.name)}, length = {spec.length}, "
            f"add = M.add_{spec.layout.name}, pad_mode = {_lua_string(spec.pad_mode)}, "
            f"fixed_only = {'true' if spec.fixed_only else 'false'}, brief = {'true' if spec.brief else 'false'}, "
            f"min_q = {spec.min_q}, max_q = {max_q}, payload = {payload} }}"
        )
    out += [
        "",
        f"M.MSG_TYPE_CHECKSUM = 0x{L.ACF_MSG_TYPE_CHECKSUM:02X}",
        f"M.MSG_TYPE_CRC = 0x{L.ACF_MSG_TYPE_CRC:02X}",
        "",
        "return M",
    ]
    return "\n".join(out) + "\n"


def _emit_fields_and_adds(
    out: list[str], layouts: tuple, placeholders: list[tuple] = ()
) -> list[str]:
    """Emit M.f entries, the fields list and add_<layout>() for `layouts`; returns the field keys."""
    defs: dict[str, str] = {}
    order: list[str] = []
    for layout in layouts:
        for f in layout.fields:
            key = _field_key(layout, f)
            text = _protofield(layout, f)
            if key in defs and defs[key] != text:
                raise ValueError(
                    f"field {layout.abbr(f)} defined differently in {layout.name}"
                )
            if key not in defs:
                defs[key] = text
                order.append(key)
    for layout, f in placeholders:
        key = _field_key(layout, f)
        if key not in defs:
            defs[key] = _protofield(layout, f)
            order.append(key)
    out.append("M.f = {}")
    for key in order:
        out.append(f"M.f.{key} = {defs[key]}")
    out += ["", "M.fields = {"]
    for key in order:
        out.append(f"    M.f.{key},")
    out += ["}", ""]
    for layout in layouts:
        out.append(f"--- {layout.doc}")
        out.append(f"function M.add_{layout.name.replace('.', '_')}(tree, tvb, off)")
        for f in layout.fields:
            if f.length == 0:
                continue
            if f.repeat > 1:
                out.append(f"    for i = 0, {f.repeat - 1} do")
                out.append(
                    f"        tree:add(M.f.{_field_key(layout, f)}, tvb(off + {f.offset} + (i * {f.length}), {f.length}))"
                )
                out.append("    end")
                continue
            out.append(
                f"    tree:add(M.f.{_field_key(layout, f)}, tvb(off + {f.offset}, {f.length}))"
            )
        out += ["end", ""]
    return order


def generate_atdecc_fields() -> str:
    """The gen/atdecc_fields.lua module: ADP, ACMP, AECP, AEM payloads, descriptors."""
    from . import atdecc_layouts as A
    from . import atdecc_table as TA

    out: list[str] = [GPL_HEADER, "local M = {}", ""]
    for name in (
        "aem_command",
        "descriptor_type",
        "aem_status",
        "aecp_message_type",
        "acmp_message_type",
        "acmp_status",
        "adp_message_type",
        "aa_mode",
        "aa_status",
        "jdks_log_priority",
    ):
        vt = L.VALUE_TABLES[name]
        out.append(f"{_value_table_name(vt.name)} = {{")
        for code, title in sorted(vt.entries.items()):
            out.append(f"    [0x{code:02X}] = {_lua_string(title)},")
        out += ["}", ""]
    placeholders = [
        (A.AEM, A.AEM_PAYLOAD_RAW),
        (A.DESCRIPTOR_LAYOUTS["DescriptorControl"], A.DESCRIPTOR_RAW),
        (A.JDKS_LOG, A.JDKS_LOG_TEXT),
    ]
    _emit_fields_and_adds(out, A.ATDECC_LAYOUTS, placeholders)

    def fkey(layout, f):
        return f"M.f.{_field_key(layout, f)}"

    out.append("M.AEM_PAYLOAD_RAW = " + fkey(A.AEM, A.AEM_PAYLOAD_RAW))
    out.append("M.AECP_PAYLOAD = " + fkey(A.AECP, A.AECP_PAYLOAD))
    out.append("M.AA_TLV_DATA = " + fkey(A.AA_TLV, A.AA_TLV_DATA))
    out.append("M.VU_PAYLOAD = " + fkey(A.VU, A.VU_PAYLOAD))
    out.append(
        "M.DESCRIPTOR_RAW = "
        + fkey(A.DESCRIPTOR_LAYOUTS["DescriptorControl"], A.DESCRIPTOR_RAW)
    )
    out.append("M.JDKS_LOG_TEXT = " + fkey(A.JDKS_LOG, A.JDKS_LOG_TEXT))
    out.append("")
    out.append(
        "--- command code -> { cmd = spec, rsp = spec }; spec = { name, length, add, trailer }"
    )
    out.append("M.aem_payloads = {}")
    for code, (cmd, rsp) in sorted(A.AEM_PAYLOADS.items()):

        def spec(p):
            if p is None:
                return "nil"
            trailer = _lua_string(p.trailer) if p.trailer else "nil"
            return f"{{ name = {_lua_string(p.name)}, length = {p.length}, add = M.add_{p.layout.name.replace('.', '_')}, trailer = {trailer} }}"

        out.append(
            f"M.aem_payloads[0x{code:04X}] = {{ cmd = {spec(cmd)}, rsp = {spec(rsp)} }}"
        )
    out.append("")
    out.append(
        "--- descriptor type -> { name, length, add, trailer = { count_field_offset, offset_field_offset, element, element_size, element_add } }"
    )
    out.append("M.descriptors = {}")
    for code, d in sorted(A.DESCRIPTORS.items()):
        trailer = "nil"
        if d.trailer is not None:
            members = {m["name"]: m for m in TA.DESCRIPTOR_STRUCTS[d.struct]["members"]}
            count_off = members[d.trailer.count_field]["offset"]
            offset_off = members[d.trailer.offset_field]["offset"]
            elem_add = (
                f"M.add_{A.TRAILER_ELEMENTS[d.trailer.element].name.replace('.', '_')}"
                if d.trailer.element in A.TRAILER_ELEMENTS
                else "nil"
            )
            trailer = (
                f"{{ count_field_offset = {count_off}, offset_field_offset = {offset_off}, "
                f"element = {_lua_string(d.trailer.element)}, element_size = {d.trailer.element_size}, element_add = {elem_add} }}"
            )
        out.append(
            f"M.descriptors[0x{code:04X}] = {{ name = {_lua_string(d.name)}, length = {d.length}, "
            f"add = M.add_{d.layout.name.replace('.', '_')}, trailer = {trailer} }}"
        )
    out.append("")
    out.append(
        f"M.AUDIO_MAPPING_LENGTH = {TA.AEM_PAYLOAD_STRUCTS['AemAudioMapping']['length']}"
    )
    out.append(f"M.JDKS_CONTROL_LOG_TEXT = {_lua_string(TA.JDKS_CONTROL_LOG_TEXT)}")
    out.append(
        f"M.JDKS_CONTROL_IPV4_PARAMETERS = {_lua_string(TA.JDKS_CONTROL_IPV4_PARAMETERS)}"
    )
    out.append(f"M.JDKS_LOG_BLOB_LENGTH = {TA.JDKS_LOG_BLOB['length']}")
    out.append(f"M.JDKS_IPV4_PARAMS_LENGTH = {TA.JDKS_IPV4_PARAMS['length']}")
    out.append(f"M.AECP_HEADER_LENGTH = {A.AECP_HEADER_LENGTH}")
    out.append(f"M.AEM_HEADER_LENGTH = {A.AEM_HEADER_LENGTH}")
    out.append(f"M.AA_HEADER_LENGTH = {A.AA_HEADER_LENGTH}")
    out.append(f"M.VU_HEADER_LENGTH = {A.VU_HEADER_LENGTH}")
    out.append("")
    out.append("return M")
    return "\n".join(out) + "\n"
